#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:import RiseInTransition kivy.uix.screenmanager.RiseInTransition

### ADICIONAR TODAS AS TELAS AQUI
<WindowManager>
    transition: NoTransition()
    LoginScreen:
        name: 'login_screen'
    RegisterScreen:
        name: 'register_screen'
    CustomizeScreen:
        name: 'customize_screen'